# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [13]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [14]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1,2,3])
print(a1.shape, a1)
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1,2],[2,4]])
print(a2.shape, a2)

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1,2],[2,4]],[[1,2],[2,4]]])
print(a3.shape, a3)


(3,) [1 2 3]
(2, 2) [[1 2]
 [2 4]]
(2, 2, 2) [[[1 2]
  [2 4]]

 [[1 2]
  [2 4]]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [19]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [20]:
# Attributes of 2-dimensional array
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)

((2, 2), 2, dtype('int64'), 4, numpy.ndarray)

In [21]:
# Attributes of 3-dimensional array
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)

((2, 2, 2), 3, dtype('int64'), 8, numpy.ndarray)

In [27]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
frame = pd.DataFrame(a3[0])
frame

0  1
0  1  2
1  2  4

In [29]:
# Create an array of shape (10, 2) with only ones
a4 = np.ones(shape=(10,2), dtype=int)
a4

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [31]:
# Create an array of shape (7, 2, 3) of only zeros
a5 = np.zeros(shape=(7,2,3), dtype=int)
a5

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [33]:
# Create an array within a range of 0 and 100 with step 3
a6 = np.arange(0, 100, 3, dtype=int)
a6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [34]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a6 = np.random.randint(0, 10, size=(7,2), dtype=int)
a6

array([[1, 8],
       [4, 0],
       [0, 6],
       [5, 8],
       [1, 2],
       [7, 9],
       [3, 9]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a7 = np.random.rand(3,5)
a7

array([[0.78435385, 0.10328559, 0.00834395, 0.8181227 , 0.56245846],
       [0.78364452, 0.4903772 , 0.27764465, 0.7332298 , 0.59424665],
       [0.50643285, 0.05123846, 0.45728788, 0.15581629, 0.91589798]])

In [38]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a8 = np.random.rand(4,6)
a8

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [44]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a9 = np.random.rand(3,7)

# Find the unique numbers in the array you just created
a9, np.unique(a9)

(array([[0.63755747, 0.88721274, 0.47221493, 0.11959425, 0.71324479,
         0.76078505, 0.5612772 ],
        [0.77096718, 0.4937956 , 0.52273283, 0.42754102, 0.02541913,
         0.10789143, 0.03142919],
        [0.63641041, 0.31435598, 0.50857069, 0.90756647, 0.24929223,
         0.41038292, 0.75555114]]),
 array([0.02541913, 0.03142919, 0.10789143, 0.11959425, 0.24929223,
        0.31435598, 0.41038292, 0.42754102, 0.47221493, 0.4937956 ,
        0.50857069, 0.52273283, 0.5612772 , 0.63641041, 0.63755747,
        0.71324479, 0.75555114, 0.76078505, 0.77096718, 0.88721274,
        0.90756647]))

In [45]:
# Find the 0'th index of the latest array you created
a9[0], np.unique(a9)[0]

(array([0.63755747, 0.88721274, 0.47221493, 0.11959425, 0.71324479,
        0.76078505, 0.5612772 ]),
 0.02541912674409519)

In [48]:
# Get the first 2 rows of latest array you created
a9.shape, a9[:2]

((3, 7),
 array([[0.63755747, 0.88721274, 0.47221493, 0.11959425, 0.71324479,
         0.76078505, 0.5612772 ],
        [0.77096718, 0.4937956 , 0.52273283, 0.42754102, 0.02541913,
         0.10789143, 0.03142919]]))

In [49]:
# Get the first 2 values of the first 2 rows of the latest array
a9.shape, a9[:2, :2]

((3, 7),
 array([[0.63755747, 0.88721274],
        [0.77096718, 0.4937956 ]]))

In [53]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a10 = np.random.randint(0, 10, size=(3,5), dtype=int)
a11 = np.ones(shape=(3,5), dtype=int)
a10, a11

(array([[0, 0, 1, 1, 5],
        [6, 4, 0, 0, 2],
        [1, 4, 9, 5, 6]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [55]:
# Add the two arrays together
a12 = a10 + a11
a12

array([[ 1,  1,  2,  2,  6],
       [ 7,  5,  1,  1,  3],
       [ 2,  5, 10,  6,  7]])

In [56]:
# Create another array of ones of shape (5, 3)
a13 = np.ones(shape=(5,3), dtype=int)
a13

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [58]:
# Try add the array of ones and the other most recent array together
a14 = a12 + a13.T
a14

array([[ 2,  2,  3,  3,  7],
       [ 8,  6,  2,  2,  4],
       [ 3,  6, 11,  7,  8]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [59]:
# Create another array of ones of shape (3, 5)
a15 = np.ones(shape=(3,5), dtype=int)
a15

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [62]:
# Subtract the new array of ones from the other most recent array
a16 = a14 - a15
a16, a16 == a12

(array([[ 1,  1,  2,  2,  6],
        [ 7,  5,  1,  1,  3],
        [ 2,  5, 10,  6,  7]]),
 array([[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]))

In [63]:
# Multiply the ones array with the latest array
a17 = a16 * a15
a17

array([[ 1,  1,  2,  2,  6],
       [ 7,  5,  1,  1,  3],
       [ 2,  5, 10,  6,  7]])

In [64]:
# Take the latest array to the power of 2 using '**'
a18 = a17 ** 2
a18

array([[  1,   1,   4,   4,  36],
       [ 49,  25,   1,   1,   9],
       [  4,  25, 100,  36,  49]])

In [65]:
# Do the same thing with np.square()
a19 = np.square(a17)
a19 == a18

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [68]:
# Find the mean of the latest array using np.mean()
mean = np.mean(a19)
mean == np.sum(a19)/a19.size

True

In [69]:
# Find the maximum of the latest array using np.max()
max = np.max(a19)
max

100

In [70]:
# Find the minimum of the latest array using np.min()
min = np.min(a19)
min

1

In [71]:
# Find the standard deviation of the latest array
sd = np.std(a19)
sd

26.884940022250372

In [72]:
# Find the variance of the latest array
var = np.var(a19)
var

722.8

In [73]:
# Reshape the latest array to (3, 5, 1)
a20 = a19.reshape(3,5,1)
a20

array([[[  1],
        [  1],
        [  4],
        [  4],
        [ 36]],

       [[ 49],
        [ 25],
        [  1],
        [  1],
        [  9]],

       [[  4],
        [ 25],
        [100],
        [ 36],
        [ 49]]])

In [75]:
# Transpose the latest array
a21 = a20.T
a21, a21.shape

(array([[[  1,  49,   4],
         [  1,  25,  25],
         [  4,   1, 100],
         [  4,   1,  36],
         [ 36,   9,  49]]]),
 (1, 5, 3))

What does the transpose do?

In [78]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a22 = np.random.randint(0, 10, size=(3,3))
a23 = np.random.randint(0, 10, size=(3,2))
a22, a23

(array([[3, 3, 2],
        [9, 2, 2],
        [3, 6, 3]]),
 array([[8, 0],
        [7, 6],
        [1, 7]]))

In [79]:
# Perform a dot product on the two newest arrays you created
a24 = a22.dot(s23)
a24

array([[25, 43],
       [55, 65],
       [30, 69]])

In [81]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a25 = np.random.randint(0, 10, size=(4,3))
a26 = np.random.randint(0, 10, size=(4,3))
a25, a26

(array([[5, 7, 0],
        [7, 3, 0],
        [7, 3, 5],
        [7, 3, 2]]),
 array([[8, 2, 8],
        [1, 1, 1],
        [5, 2, 8],
        [3, 0, 3]]))

In [82]:
# Perform a dot product on the two newest arrays you created
a25.dot(a26)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [83]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a27 = a25.dot(a26.T)
a27

array([[ 54,  12,  39,  15],
       [ 62,  10,  41,  21],
       [102,  15,  81,  36],
       [ 78,  12,  57,  27]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [85]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a28 = np.random.randint(0, 10, size=(2,3))
a29 = np.random.randint(0, 10, size=(2,3))
a28, a29

(array([[5, 5, 5],
        [2, 5, 7]]),
 array([[1, 4, 0],
        [0, 4, 2]]))

In [86]:
# Compare the two arrays with '>'
a28 > a29

array([[ True,  True,  True],
       [ True,  True,  True]])

What happens when you compare the arrays with `>`?

In [87]:
# Compare the two arrays with '>='
a28 >= a29

array([[ True,  True,  True],
       [ True,  True,  True]])

In [88]:
# Find which elements of the first array are greater than 7
a30 = a28 > 7
a30

array([[False, False, False],
       [False, False, False]])

In [89]:
# Which parts of each array are equal? (try using '==')
a28 == a29

array([[False, False, False],
       [False, False, False]])

In [97]:
# Sort one of the arrays you just created in ascending order
a30 = np.random.randint(0, 10, size=(3,3))
a30, np.sort(a30)

(array([[7, 0, 4],
        [2, 0, 3],
        [4, 6, 0]]),
 array([[0, 4, 7],
        [0, 2, 3],
        [0, 4, 6]]))

In [99]:
# Sort the indexes of one of the arrays you just created
a30, np.sort(a30[0])

(array([[7, 0, 4],
        [2, 0, 3],
        [4, 6, 0]]),
 array([0, 4, 7]))

In [100]:
# Find the index with the maximum value in one of the arrays you've created
np.max(a30)

7

In [101]:
# Find the index with the minimum value in one of the arrays you've created
np.min(a30)

0

In [103]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
a30, np.max(a30,axis=1), np.argmax(a30, axis=1)

(array([[7, 0, 4],
        [2, 0, 3],
        [4, 6, 0]]),
 array([7, 3, 6]),
 array([0, 2, 1]))

In [104]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
a30, np.min(a30, axis=0), np.argmin(a30, axis=0)

(array([[7, 0, 4],
        [2, 0, 3],
        [4, 6, 0]]),
 array([2, 0, 0]),
 array([1, 0, 2]))

In [105]:
# Create an array of normally distributed random numbers
a31 = np.random.normal(size=10)
a31

array([-0.92604662, -0.51296532,  0.71010924,  0.09247887,  0.63007494,
        1.76293747,  0.23095372, -0.80893689,  1.05742351,  0.05136086])

In [113]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.random.seed(3)
a32 = np.linspace(1, 100, 10, dtype=int)
a32

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.